// <auto-generated />
namespace MEGATECH.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Thay_Doi_Thong_Tin_Khach_Hang : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Thay_Doi_Thong_Tin_Khach_Hang));
        
        string IMigrationMetadata.Id
        {
            get { return "202505101628337_Thay_Doi_Thong_Tin_Khach_Hang"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
